# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, java, cpp, js, go]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ${{ matrix.language }}
        run: |
          if [ "${{ matrix.language }}" == "python" ]; then
            python -m pip install --upgrade pip;
          elif [ "${{ matrix.language }}" == "java" ]; then
            sudo apt-get update;
            sudo apt-get install -y maven;
          elif [ "${{ matrix.language }}" == "cpp" ]; then
            sudo apt-get update;
            sudo apt-get install -y build-essential;
          elif [ "${{ matrix.language }}" == "js" ]; then
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -;
            sudo apt-get install -y nodejs;
          elif [ "${{ matrix.language }}" == "go" ]; then
            wget https://go.dev/dl/go1.21.5.linux-amd64.tar.gz;
            sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz;
            echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV;
          fi

      - name: Install Dependencies and Run Tests
        run: |
          if [ "${{ matrix.language }}" == "python" ]; then
            pip install -r requirements.txt || true;
            python -m unittest discover -v languages/python/tests;
          elif [ "${{ matrix.language }}" == "java" ]; then
            mvn -f languages/java clean test;
          elif [ "${{ matrix.language }}" == "cpp" ]; then
            g++ languages/cpp/*/*.cpp -std=c++17 -o cpp_tests;
            ./cpp_tests;
          elif [ "${{ matrix.language }}" == "js" ]; then
            cd languages/js;
            npm install || true;
            npm test;
          elif [ "${{ matrix.language }}" == "go" ]; then
            cd languages/go;
            go test ./...;
          fi
