name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, java, cpp, js, go, csharp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ${{ matrix.language }}
        run: |
          LANGUAGE="${{ matrix.language }}"

          if [ "$LANGUAGE" = "python" ]; then
            python -m pip install --upgrade pip

          elif [ "$LANGUAGE" = "java" ]; then
            sudo apt-get update
            sudo apt-get install -y maven

          elif [ "$LANGUAGE" = "cpp" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential

          elif [ "$LANGUAGE" = "js" ]; then
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

          elif [ "$LANGUAGE" = "go" ]; then
            wget https://go.dev/dl/go1.21.5.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
            echo "PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV
          fi

      - name: Setup .NET
        if: matrix.language == 'csharp'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Install dependencies and run tests
        run: |
          LANGUAGE="${{ matrix.language }}"

          if [ "$LANGUAGE" = "python" ]; then
            export PYTHONPATH=languages/python
            [ -f languages/python/requirements.txt ] && pip install -r languages/python/requirements.txt
            [ -d languages/python/tests ] && python -m unittest discover -v languages/python/tests

          elif [ "$LANGUAGE" = "java" ]; then
            [ -f languages/java/pom.xml ] && mvn -f languages/java clean test

          elif [ "$LANGUAGE" = "cpp" ]; then
            cpp_files=$(find languages/cpp -name "*.cpp")
            if [ -n "$cpp_files" ]; then
              g++ $cpp_files -std=c++17 -o cpp_tests && ./cpp_tests
            fi

          elif [ "$LANGUAGE" = "js" ]; then
            if [ -f languages/js/package.json ]; then
              cd languages/js
              npm install
              npm test
            fi

          elif [ "$LANGUAGE" = "go" ]; then
            export PATH="/usr/local/go/bin:$PATH"
            [ -f languages/go/go.mod ] && cd languages/go && go test ./...

          elif [ "$LANGUAGE" = "csharp" ]; then
            if [ -f languages/csharp/Project.csproj ]; then
              cd languages/csharp
              dotnet restore
              dotnet test
            fi
          fi
